#FORMAT GENERIC
f_string = 'Ray sist'
print(f'nama = {f_string}')
f_int = 2893
print(f'a = {f_int}')
f_float = 2873.2431
print(f'b = {f_float}')
f_bool = True
print(f'c = {f_bool}')
f_ribuan = 178263
print(f'd = {f_ribuan:,}')
f_desimal = 178.28465823478
print(f'd = {f_desimal:.5f}')
f_leading =142.27
print(f'leading zero = {f_leading:0.3f}')
f_persen = 0.267
print(f'presentase = {f_persen:.2%}')
x = 27
y = 2
print(f'{x} - {y} = {x-y}')
z = 255 #binary, octal, hex
print(f'{z} dalam binary = {bin(z)}')
print(f'{z} dalam octal = {oct(z)}')
print(f'{z} dalam hex = {hex(z)}')
